dhl_api_integration.settings:
  type: config_object
  label: 'DHL API settings'
  mapping:
    api_base_url:
      type: string
      label: 'API Base URL'
    api_key:
      type: string
      label: 'API Key'
